server:
  port: 8090

spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://43.143.68.96:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
  ai:
    openai:
      base-url: https://pro-share-aws-api.zcyai.com/
      api-key: sk-uEA6GlHv4M5QyqWP8f565aF0108a4c859082Af3c462d2f6a
      embedding-model: text-embedding-ada-002
      embedding:
        options:
          num-batch: 1536
    ollama:
      base-url: http://7ede12321d85447fb69d-deepseek-r1-llm-api.gcs-xy1a.jdcloud.com/
      mode:
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 768

logging:
  level:
    root: info
  config: classpath:logback-spring.xml